# Generated by Django 3.2.8 on 2022-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_globalconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'user')], max_length=32, null=True),
        ),
    ]
