# invoice_config_staging.yaml file

PUB_KEY: pk_test_51MGeSgLN0C8PbbSaxqzV70km0tvzZeZ29amk7P6SMlHqS9H84fLYinRLvYHDle3d5zoMlFrUzdWofuqXfMsI0zAT00f3TmvCkB
SEC_KEY: sk_test_51MGeSgLN0C8PbbSaqa00yChu1zcxNqhzozndgSAcJsB5j20WnPFLOpQm7Y2odrp0C3kFFB30TlgqDikiDP4WSN8R00jW071IBC

