# Generated by Django 3.2.8 on 2022-12-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0005_auto_20220826_0603'),
        ('subscription_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ref_id', models.CharField(blank=True, max_length=64, null=True)),
                ('card_token', models.CharField(blank=True, max_length=64, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('i_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pay_token', models.CharField(blank=True, max_length=64, null=True)),
                ('i_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe_payment_module.customer')),
                ('i_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription_module.plan')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
