# Generated by Django 3.2.8 on 2022-12-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0002_auto_20221222_1153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
