# Generated by Django 3.2.8 on 2022-12-22 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0004_invoice_next_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='next_invoice',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
