# Generated by Django 3.2.8 on 2022-12-23 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0005_auto_20221222_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='from_date',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_date',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
