# Generated by Django 3.2.8 on 2023-01-02 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0007_auto_20221223_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
