# Generated by Django 3.2.8 on 2023-01-02 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0008_invoice_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
