# Generated by Django 3.2.8 on 2023-01-02 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0009_alter_invoice_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
