# Generated by Django 3.2.8 on 2023-01-04 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0011_alter_invoice_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='from_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
