# Generated by Django 3.2.8 on 2023-01-04 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0012_auto_20230104_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
