# Generated by Django 3.2.8 on 2023-01-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0013_auto_20230104_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_paid',
        ),
    ]
