# Generated by Django 3.2.8 on 2023-01-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0014_auto_20230109_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='i_customer',
        ),
    ]
