# Generated by Django 3.2.8 on 2023-03-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment_module', '0015_remove_payment_i_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'extra_services',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='onetime',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExtraServicesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('i_extraservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_payment_module.extraservices')),
                ('i_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_payment_module.invoice')),
            ],
            options={
                'db_table': 'extra_services_mapping',
            },
        ),
    ]
