# Generated by Django 3.2.8 on 2022-12-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0005_auto_20220826_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('days_per_interval', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'monthly'), ('annually', 'annually')], default='monthly', max_length=50)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('renewed_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_module.plan')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UserModuleUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_units', models.IntegerField()),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_module.module')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_module.subscriptions')),
            ],
            options={
                'db_table': 'user_module_units',
            },
        ),
        migrations.CreateModel(
            name='PlanModuleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_allowed', models.IntegerField()),
                ('remarks', models.TextField(max_length=500)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_module.module')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription_module.plan')),
            ],
            options={
                'db_table': 'plan_module_detail',
            },
        ),
    ]
