# Generated by Django 3.2.8 on 2022-12-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
