# Generated by Django 3.2.8 on 2023-01-05 12:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_module', '0002_auto_20221222_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
