# Generated by Django 3.2.8 on 2023-01-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_module', '0003_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='annual_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
