# Generated by Django 3.2.8 on 2023-01-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_module', '0004_plan_annual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoduleunits',
            name='profile_id',
        ),
    ]
