# Generated by Django 3.2.8 on 2023-03-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_module', '0007_alter_plan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleunits',
            name='consumed_units',
            field=models.IntegerField(default=0),
        ),
    ]
