# Generated by Django 3.2.8 on 2022-09-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteScrapyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('raw_data', models.JSONField()),
                ('process_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('rejected', 'rejected'), ('processed', 'processed')], default='queued', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'site_scrapy_data',
            },
        ),
    ]
