# Generated by Django 3.2.8 on 2022-09-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0022_contactus'),
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitescrapydata',
            name='website_url',
        ),
        migrations.AddField(
            model_name='sitescrapydata',
            name='i_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_audit.website'),
        ),
    ]
