# Generated by Django 3.2.8 on 2022-10-14 09:17

import crawler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20220929_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitescrapydata',
            name='process_data',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=crawler.models.get_process_data_file_path),
        ),
        migrations.AlterField(
            model_name='sitescrapydata',
            name='raw_data',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=crawler.models.get_raw_data_file_path),
        ),
    ]
