# Generated by Django 3.2.8 on 2023-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_websitepages'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepages',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
