# Generated by Django 3.2.8 on 2023-02-21 11:30

import crawler.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0033_userselectedwebsite_i_profile'),
        ('crawler', '0006_websitepages_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_data', models.FileField(blank=True, max_length=256, null=True, upload_to=crawler.models.get_process_data_file_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_audit.siteauditproject')),
            ],
            options={
                'db_table': 'site_process_data',
            },
        ),
    ]
