# Generated by Django 3.2.8 on 2023-02-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0033_userselectedwebsite_i_profile'),
        ('crawler', '0011_siteprocessdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprocessdata',
            name='i_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_audit.website'),
        ),
    ]
