# Generated by Django 3.2.8 on 2023-02-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_siteprocessdata_i_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprocessdata',
            name='i_website',
        ),
    ]
