# Generated by Django 3.2.8 on 2023-03-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_remove_siteprocessdata_i_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitescrapydata',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('rejected', 'rejected'), ('crawled', 'crawled'), ('processed', 'processed')], default='queued', max_length=15),
        ),
    ]
