"""
Django settings for site_checkup project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zl3cb-5a%6*7)y6xat6=zc%k2!)q&z+qada$xnbeocxy9i3^g_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'site_audit',
    'permissions',
    'rbac_preferences',
    'user_management',
    'loggings',
    'corsheaders',
    'crawler',
    'widget_tweaks',
    'bootstrap5',
    'subscription_module',
    'stripe_payment_module',
    'ckeditor',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'site_checkup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site_checkup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'site_checkup',
        'USER': 'postgres',
        'PASSWORD': 'roOt@5',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_URL = '/accounts/login/'
LOGOUT_URL = '/accounts/logout/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
AUTHENTICATION_BACKENDS = ['user_management.backends.EmailBackend']
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
API_BASE_URL = 'http://23.106.56.71:5555'
CRAWL_WEBSITE_API_URL = '%s/crawl_api/crawl_website_api_v2' % API_BASE_URL
GET_KEYWORD_FROM_WEBSITE_API_URL = '%s/crawl_api/get_keywords_from_website' % API_BASE_URL
GET_KEYWORDS_FROM_KEYWORD_API_URL = '%s/crawl_api/get_keywords_from_keyword' % API_BASE_URL
GET_SEO_SITE_DATA_API_URL = '%s/crawl_api/seo_site_analyzer' % API_BASE_URL
GET_SITE_DIAGNOSTICS_DATA_API_URL = '%s/crawl_api/site_diagnositcs' % API_BASE_URL
GET_BROKEN_LINK_API_URL = '%s/crawl_api/check_broken_links' % API_BASE_URL
GET_SERP_API_URL = '%s/crawl_api/get_serp' % API_BASE_URL
GET_LOCATION = '%s/crawl_api/get_location' % API_BASE_URL

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'noreply.departmentanalysis@gmail.com'
EMAIL_HOST_PASSWORD = 'mmoureupwjxhwlgj'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

EMAIL_TO_LEAD = 'info@websiterankingexpert.com'
# EMAIL_TO_LEAD = 'sanjay@bitswits.com'

DATA_UPLOAD_MAX_MEMORY_SIZE = 999999999999

CORS_ORIGIN_ALLOW_ALL = True
# CORS_URLS_REGEX = r"^/api/.*$"
AUDIENCE_OVERVIEW_API = 'https://app.websiterankingexpert.com/analytics/audience_overview.php'
BEHAVIOR_OVERVIEW_API = 'https://app.websiterankingexpert.com/analytics/behavior_overview.php'
ACQUISITION_OVERVIEW_API = 'https://app.websiterankingexpert.com/analytics/acquisition_overview.php'

CRAWLER_API = 'http://127.0.0.1:9000/api/crawl/'
CRAWLER_CALLBACK_URL = 'http://127.0.0.1:8000/crawler/crawl_data/'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
YAML_FILE_PATH = os.path.join(BASE_DIR, '../crys_stripe_config/stripe_config.yaml')
