# Generated by Django 3.2.8 on 2022-07-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectperiodwisedetail',
            old_name='i_site_checkup_project',
            new_name='i_site_audit_project',
        ),
        migrations.RenameField(
            model_name='siteauditjob',
            old_name='i_site_checkup_project',
            new_name='i_site_audit_project',
        ),
    ]
