# Generated by Django 3.2.8 on 2022-07-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0004_auto_20220720_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField()),
                ('website_data', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('i_site_audit_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_audit.siteauditproject')),
            ],
            options={
                'db_table': 'site_competitor',
                'unique_together': {('i_site_audit_project', 'website_url')},
            },
        ),
    ]
