# Generated by Django 3.2.8 on 2022-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0005_sitecompetitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteauditproject',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
