# Generated by Django 3.2.8 on 2022-08-01 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import site_audit.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_audit', '0007_websitebacklinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'website',
            },
        ),
        migrations.CreateModel(
            name='WebsiteBacklink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlinks_data', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('i_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_audit.website')),
            ],
            options={
                'db_table': 'website_backlink',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_seo_data', models.FileField(max_length=256, upload_to=site_audit.models.get_seo_data_file)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('i_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_audit.website')),
            ],
            options={
                'db_table': 'website_seo_data',
            },
        ),
        migrations.DeleteModel(
            name='WebsiteBacklinks',
        ),
        migrations.AddField(
            model_name='siteauditproject',
            name='i_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_audit.website'),
        ),
        migrations.AddField(
            model_name='sitecompetitor',
            name='i_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_audit.website'),
        ),
        migrations.AlterUniqueTogether(
            name='siteauditproject',
            unique_together={('i_website', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='sitecompetitor',
            unique_together={('i_site_audit_project', 'i_website')},
        ),
        migrations.RemoveField(
            model_name='siteauditproject',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='sitecompetitor',
            name='website_url',
        ),
    ]
