# Generated by Django 3.2.8 on 2022-08-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0008_auto_20220801_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_name', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'objective',
            },
        ),
        migrations.CreateModel(
            name='ObjectiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'objective_type',
            },
        ),
        migrations.CreateModel(
            name='ProjectObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_status', models.CharField(choices=[('begin', 'begin'), ('resume', 'resume'), ('skip', 'skip')], default='begin', max_length=64)),
                ('completion_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('i_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_audit.objective')),
                ('i_site_audit_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_audit.siteauditproject')),
            ],
            options={
                'db_table': 'project_objective',
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='i_objective_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_audit.objectivetype'),
        ),
    ]
