# Generated by Django 3.2.11 on 2022-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0009_auto_20220801_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='objective_desc',
            field=models.TextField(default=''),
        ),
    ]
