# Generated by Django 3.2.8 on 2022-08-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0010_objective_objective_desc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectobjective',
            unique_together={('i_site_audit_project', 'i_objective')},
        ),
    ]
