# Generated by Django 3.2.8 on 2022-08-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0012_trackkeyword'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackkeyword',
            unique_together={('i_site_audit_project', 'keyword')},
        ),
    ]
