# Generated by Django 3.2.8 on 2022-08-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0013_alter_trackkeyword_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackkeyword',
            name='tracking_end_time',
        ),
        migrations.RemoveField(
            model_name='trackkeyword',
            name='tracking_start_time',
        ),
        migrations.CreateModel(
            name='TrackKeywordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_date', models.DateTimeField()),
                ('tracking_value', models.IntegerField()),
                ('tracking_change', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('i_track_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_audit.trackkeyword')),
            ],
            options={
                'db_table': 'track_keyword_detail',
            },
        ),
    ]
