# Generated by Django 3.2.8 on 2022-08-12 13:03

from django.db import migrations, models
import site_audit.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0015_googleanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitebacklink',
            name='backlinks_data',
            field=models.FileField(max_length=256, upload_to=site_audit.models.get_backlinks_data_file),
        ),
    ]
