# Generated by Django 3.2.8 on 2022-08-16 06:59

from django.db import migrations, models
import django.db.models.deletion
import site_audit.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0016_alter_websitebacklink_backlinks_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAnchorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_text_data', models.FileField(max_length=256, upload_to=site_audit.models.get_anchor_text_file_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('i_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_audit.website')),
            ],
            options={
                'db_table': 'website_anchor_text',
            },
        ),
    ]
