# Generated by Django 3.2.8 on 2022-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0018_websiteorganickeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackkeyworddetail',
            name='tracking_date',
            field=models.DateField(),
        ),
    ]
