# Generated by Django 3.2.8 on 2022-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0020_competitortrackkeyword_competitortrackkeyworddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='objective_sub_desc',
            field=models.TextField(default=''),
        ),
    ]
