# Generated by Django 3.2.8 on 2022-10-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0022_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_data', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'google_analytics_account',
            },
        ),
    ]
