# Generated by Django 3.2.8 on 2022-10-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0025_auto_20221012_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='crawl_request_inprocess',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together={('website_url', 'crawl_request_inprocess')},
        ),
    ]
