# Generated by Django 3.2.8 on 2022-10-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0027_googleanalyticsaccount_analytics_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleanalyticsaccount',
            name='account_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
