# Generated by Django 3.2.8 on 2022-10-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0027_auto_20221026_1327'),
        ('site_audit', '0028_alter_googleanalyticsaccount_account_data'),
    ]

    operations = [
    ]
