# Generated by Django 3.2.8 on 2022-11-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0030_googleanalyticsaccount_account_data_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='error_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='error_occured',
            field=models.BooleanField(default=False),
        ),
    ]
