# Generated by Django 3.2.8 on 2023-02-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_audit', '0031_auto_20221117_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_site_audit_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_audit.siteauditproject')),
                ('i_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_audit.website')),
            ],
            options={
                'db_table': 'user_selected_website',
            },
        ),
    ]
